### ISSUE TITLE
'unrecognized token' as response from any shell commands

### ISSUE THREAD

**Issue by xLinkOut** [colental/byob#14]
I get this error everytime I send any command by shell to a client.

>Server
[luca @ /home/luca/Scrivania/byob/byob]>shell 1
Starting Reverse TCP Shell w/ Session 1...
[ 1 @ /home/luca/Scrivania/byob/byob ]>1
DEBUG:core.util:unrecognized token: "8a59b7ed3530e44d776d77a5b51afd5c"
int() argument must be a string or a number, not 'Session'

>Client
ERROR:\_\_main\_\_:kill error: dictionary changed size during iteration
ERROR:\_\_main\_\_:Connection timed out

**Comment by colental** [comment]
Thanks for bringing this issue to my attention! I think I know what the problem is, I'll fix it and update it shortly!

**Comment by colental** [comment]
Okay the issue should be fixed - try it out!

**Comment by xLinkOut** [comment]
Issue persist...

[luca @ /home/luca/Scrivania/botnet/byob/byob]>shell 1
Starting Reverse TCP Shell w/ Session 1...
[ 1 @ /home/luca/Scrivania/botnet/byob/byob ]>help
int() argument must be a string or a number, not 'Session'

And dropper close itself. :/
