### ISSUE TITLE
Bug: SimpleHTTPServer processes linger after exiting

### ISSUE THREAD

**Issue by mshirley** [colental/byob#20]
execute netstat to check for existing processes listening on default ports.
```
user@userbox:~/src/byob/byob$ sudo netstat -alnp | grep -E '1337|1338|1339'
```
start server
```
python server.py
```
check for processes listening.
```
user@userbox:~/src/byob/byob$ sudo netstat -alnp | grep -E '1337|1338|1339'
tcp        0      0 0.0.0.0:1337            0.0.0.0:*               LISTEN      29609/python
tcp        0      0 0.0.0.0:1338            0.0.0.0:*               LISTEN      29613/python
tcp        0      0 0.0.0.0:1339            0.0.0.0:*               LISTEN      29611/python
```
exit server gracefully
```exit```
check netstat for porcesses listening again.
```
user@userbox:~/src/byob/byob$ sudo netstat -alnp | grep -E '1337|1338|1339'
tcp        0      0 0.0.0.0:1338            0.0.0.0:*               LISTEN      29613/python
tcp        0      0 0.0.0.0:1339            0.0.0.0:*               LISTEN      29611/python
```
the two processes running SimpleHTTPServer that are spawned and not properly cleaned up after graceful exit.  this causes a number of issues.

**Comment by colental** [comment]
Good catch! The issue should now be fixed, try it out and let me know. By the way, I really appreciate all your contributions to the project - feel free to email me anytime at danielvegamyhre@gmail.com, I always do my best to respond quickly and it may be useful to have a more direct line of communication during the development process.

**Comment by mshirley** [comment]
this is still an issue in linux.

a fix for this is to follow this stack overflow article.

https://stackoverflow.com/questions/4789837/how-to-terminate-a-python-subprocess-launched-with-shell-true/4791612#4791612

i implemented this and it seems to be working in linux but may not work in windows and mac.

```    
globals()['package_handler'] = subprocess.Popen('{} -m SimpleHTTPServer {}'.format(sys.executable, options.port + 2), 0, None, subprocess.PIPE, subprocess.PIPE, subprocess.PIPE, cwd=packages, shell=True, preexec_fn=os.setsid)
globals()['module_handler'] = subprocess.Popen('{} -m SimpleHTTPServer {}'.format(sys.executable, options.port + 1), 0, None, subprocess.PIPE, subprocess.PIPE, subprocess.PIPE, cwd=modules, shell=True, preexec_fn=os.setsid)
```
```
os.killpg(os.getpgid(globals()['package_handler'].pid), signal.SIGTERM)
os.killpg(os.getpgid(globals()['module_handler'].pid), signal.SIGTERM)
```
