### ISSUE TITLE
Installation Documentation

### ISSUE THREAD

**Issue by aminvakil** [colental/byob#9]
It executes correctly and doesn't show any error neither in server nor client.
But it doesn't listen on ports I say in implementation 
`python server.py --host a.b.c.d --port 8000 `
And in client it doesn't get me any error and says:
```
[>] Modules
	Adding modules...- (4 modules added to client)
[>] Imports
	Adding imports...- (33 imports from 4 modules)
[>] Payload
	Uploading payload... - (hosting payload at: http://1.1.1.1:8001//payloads/rRh.py)
[>] Stager
	Uploading stager... - (hosting stager at: http://1.1.1.1:8001//stagers/rRh.py)
[>] Dropper
(saved to file: byob_rRh.py)
```
(I executed `python client.py 1.1.1.1 8000`)
I ain't no python expert and most probably the fault is on me, but could you please write an installation documentation?

**Comment by colental** [comment]
Thanks for the feedback! This is actually a bug that I am currently fixing right now - I'll keep this issue open until it's fixed!

**Comment by colental** [comment]
Ok this issue should now be fixed

**Comment by aminvakil** [comment]
Sorry to bother you again, I still can't find installation doucmentation.

**Comment by aminvakil** [comment]
https://github.com/malwaredllc/byob/wiki
